-- Migration 011: Expand the Scenario Templates Library to 50+ entries.
--
-- 010_seed_starter_content.sql seeded 8 starter templates. This adds
-- 50 more across a much wider range of everyday scenarios (work, dating,
-- family, money, roommates, friendship, parenting) so the library
-- actually functions as a browsable, searchable catalog rather than a
-- handful of examples. All premium = FALSE / active = TRUE, so every
-- row is visible to every account regardless of plan.
--
-- Depends on: 010_seed_starter_content.sql

BEGIN;

INSERT INTO templates (id, title, category, description, template_text, goal, scenario, premium, active, sort_order) VALUES
  ('tpl_group_trip_bailout', 'Backing out of a group trip', 'Social', 'Cancel on a planned group trip without wrecking everyone''s plans.',
   'Hey all — I have to drop out of the trip, I''m really sorry for the short notice. Please don''t let this change your plans, and let me know if there''s a cost I should cover for my share.',
   'exit cleanly', 'group trip cancellation', FALSE, TRUE, 100),
  ('tpl_wedding_decline', 'Declining a wedding invitation', 'Social', 'Say no to a wedding without it reading as a snub.',
   'Congratulations again on the engagement! I won''t be able to make it on [date], but I''m so happy for you both and would love to celebrate with you another way.',
   'decline warmly', 'wedding invitation', FALSE, TRUE, 110),
  ('tpl_birthday_no_gift', 'Skipping a gift exchange', 'Social', 'Opt out of a gift exchange or expensive group gift without seeming cheap.',
   'I''m going to sit this one out for the group gift this year — happy to still contribute a card or help organize, just can''t do the amount this time.',
   'set a boundary without guilt', 'gift exchange', FALSE, TRUE, 120),
  ('tpl_friend_money_lent', 'Asking a friend to repay a loan', 'Money', 'Bring up money a friend borrowed without turning it into a fight.',
   'Hey, not trying to make this weird, but could you pay back the [amount] from [date] when you get a chance? No rush on timing, just wanted to put it back on your radar.',
   'get repaid without damaging the friendship', 'friend loan repayment', FALSE, TRUE, 130),
  ('tpl_late_rent', 'Telling a landlord rent will be late', 'Money', 'Give a landlord a heads-up before rent is late instead of after.',
   'Hi [landlord], I wanted to give you advance notice that rent will be a few days late this month due to [reason]. I expect to have it to you by [date] — let me know if that works.',
   'get ahead of the problem', 'late rent notice', FALSE, TRUE, 140),
  ('tpl_price_negotiation', 'Negotiating a freelance rate', 'Money', 'Counter a client''s low offer without losing the project.',
   'Thanks for sending this over — the scope looks great. My rate for work like this is [amount], which reflects [reason]. Happy to talk through options if that''s outside budget.',
   'hold your rate', 'freelance rate negotiation', FALSE, TRUE, 150),
  ('tpl_split_bill_uneven', 'Bringing up an uneven bill split', 'Money', 'Address a friend who consistently underpays on shared bills.',
   'Quick thing — I noticed the last few times we''ve split things, it''s ended up a bit uneven in my direction. Can we double check and settle up, and maybe split more carefully going forward?',
   'fix the pattern without an argument', 'uneven bill splitting', FALSE, TRUE, 160),
  ('tpl_subscription_cancel_pushback', 'Pushing back on a retention offer', 'Money', 'Firmly cancel a subscription despite a retention agent''s pushback.',
   'I appreciate the offer, but I''d like to go ahead and cancel my subscription today. Please don''t transfer me to another department — just process the cancellation.',
   'cancel without getting talked out of it', 'subscription cancellation', FALSE, TRUE, 170),
  ('tpl_salary_negotiation_offer', 'Negotiating a job offer', 'Work', 'Counter a job offer without risking it being pulled.',
   'Thank you so much for the offer — I''m genuinely excited about the role. Based on my experience and the market for this position, I was hoping we could look at [amount]. Is there flexibility there?',
   'negotiate respectfully', 'job offer negotiation', FALSE, TRUE, 180),
  ('tpl_declining_extra_work', 'Declining extra work outside your role', 'Work', 'Say no to an out-of-scope ask from a colleague without seeming unhelpful.',
   'I''d love to help, but this falls outside what I''m resourced for right now. Let''s loop in [manager] to see if it should be prioritized against my current work.',
   'protect your workload', 'extra work request', FALSE, TRUE, 190),
  ('tpl_meeting_that_could_be_email', 'Suggesting a meeting be cancelled', 'Work', 'Push to cancel or shorten an unnecessary meeting.',
   'Looking at the agenda, I think this could be handled async — want me to send a summary doc instead and we can regroup only if questions come up?',
   'reduce meeting load', 'unnecessary meeting', FALSE, TRUE, 200),
  ('tpl_credit_stealing_coworker', 'Addressing a coworker taking credit', 'Work', 'Reclaim credit for your work without a public confrontation.',
   'Hey, wanted to flag — in the meeting it sounded like [project] was solely your work, and I want to make sure my contribution on [part] is visible too. Can we align on how we present it going forward?',
   'reclaim credit calmly', 'coworker taking credit', FALSE, TRUE, 210),
  ('tpl_layoff_conversation', 'Delivering a layoff notice', 'Work', 'Deliver difficult news to a direct report with clarity and care.',
   'I have some difficult news to share. Due to [reason], your position is being eliminated effective [date]. This isn''t a reflection of your work, and I want to walk you through next steps and support available.',
   'deliver hard news humanely', 'layoff notification', FALSE, TRUE, 220),
  ('tpl_performance_feedback', 'Giving critical performance feedback', 'Work', 'Deliver tough feedback to a direct report without it landing as an attack.',
   'I want to talk through some patterns I''ve noticed in [area] — specifically [example]. My goal is to help you course-correct, not pile on, so let''s figure out a plan together.',
   'deliver feedback constructively', 'performance feedback', FALSE, TRUE, 230),
  ('tpl_declining_reference', 'Declining to give a reference', 'Work', 'Turn down a reference request without burning the relationship.',
   'I don''t think I''m the strongest reference for this particular role given [reason] — I want you to have the best shot, so I think someone like [alternative] might represent you better.',
   'decline honestly', 'reference request decline', FALSE, TRUE, 240),
  ('tpl_resignation_letter', 'Announcing your resignation', 'Work', 'Give notice to your manager clearly and professionally.',
   'I wanted to let you know that I''ve decided to resign from my role, with my last day being [date]. I''m grateful for my time here and want to make the transition as smooth as possible.',
   'resign cleanly', 'resignation announcement', FALSE, TRUE, 250),
  ('tpl_counter_resignation_offer', 'Turning down a counteroffer', 'Work', 'Decline a counteroffer after resigning without reopening the conversation.',
   'I really appreciate you putting this together, but I''ve decided to move forward with the new opportunity. My decision isn''t about the offer itself — it''s the right next step for me.',
   'hold your decision', 'counteroffer decline', FALSE, TRUE, 260),
  ('tpl_ask_for_flexible_hours', 'Requesting flexible work hours', 'Work', 'Ask a manager for a schedule change without sounding like a complaint.',
   'I''d like to propose shifting my hours to [new schedule] to better support [reason]. My deliverables and availability for meetings wouldn''t change — just wanted to check if that works on your end.',
   'get a yes', 'flexible hours request', FALSE, TRUE, 270),
  ('tpl_declining_promotion', 'Declining a promotion or new role', 'Work', 'Turn down an offered promotion without it reading as disinterest in growth.',
   'I really appreciate you considering me for this — after thinking it through, I don''t think now is the right time for me to take it on, for [reason]. I''d love to talk about what growth could look like down the line.',
   'decline while staying ambitious', 'promotion decline', FALSE, TRUE, 280),
  ('tpl_networking_cold_ask', 'Cold outreach for a coffee chat', 'Work', 'Ask someone you admire professionally for time without sounding presumptuous.',
   'I''ve been following your work on [topic] and would love 15 minutes to hear how you approached [specific thing] — completely understand if your schedule doesn''t allow it.',
   'get a yes to a cold ask', 'networking cold outreach', FALSE, TRUE, 290),
  ('tpl_second_date_yes_but', 'Proposing a change to a second date', 'Dating', 'Say yes to a second date but suggest a different activity or pace.',
   'I had a really nice time! I''d love to see you again — would you be up for [different activity] next time instead of [original activity]?',
   'steer the next date', 'second date proposal', FALSE, TRUE, 300),
  ('tpl_ghosted_reconnect', 'Reconnecting after going quiet', 'Dating', 'Re-open a conversation after disappearing without a clean explanation, without over-apologizing.',
   'Hey — I know I went quiet for a bit, that''s on me. I''d still like to talk if you''re open to it, no pressure either way.',
   'reopen the door respectfully', 'reconnect after ghosting', FALSE, TRUE, 310),
  ('tpl_defining_relationship', 'Bringing up ''what are we''', 'Dating', 'Ask about relationship status without pressuring an answer.',
   'I''ve been enjoying spending time together and wanted to check in on where you see this going — no pressure to have a perfect answer, just want to be on the same page.',
   'open the conversation', 'define the relationship', FALSE, TRUE, 320),
  ('tpl_breakup_message', 'Ending a relationship respectfully', 'Dating', 'End a relationship clearly and kindly, in person or by message when necessary.',
   'I''ve thought about this a lot, and I don''t think we''re right for each other long-term. I care about you and wanted to be honest rather than let this drag on.',
   'end it clearly', 'relationship breakup', FALSE, TRUE, 330),
  ('tpl_declining_second_date', 'Turning down a second date', 'Dating', 'Decline a second date after a first that didn''t spark interest.',
   'I had a nice time getting to know you, but I don''t think there''s a romantic connection on my end. Wishing you the best in your search.',
   'decline kindly', 'second date decline', FALSE, TRUE, 340),
  ('tpl_dating_boundary_pace', 'Setting a pace boundary while dating', 'Dating', 'Ask to slow down without shutting the relationship down.',
   'I''m really enjoying this, and I want to be honest that I''d like to take things a bit slower — it''s not about you, it''s just how I move through new relationships.',
   'set a pace boundary', 'dating pace boundary', FALSE, TRUE, 350),
  ('tpl_family_holiday_decline', 'Skipping a family holiday gathering', 'Family', 'Say no to attending a family holiday event without a blowout.',
   'I''ve decided not to make it to [event] this year — I know that''s disappointing, and I still love you all. I''ll plan a separate time to see everyone.',
   'hold the boundary', 'holiday gathering decline', FALSE, TRUE, 360),
  ('tpl_parent_unsolicited_advice', 'Responding to unsolicited parenting advice', 'Family', 'Push back on unwanted parenting advice from a relative without a rift.',
   'I know you mean well, and I want to do this my way for [reason] — I''ll definitely come to you if I want input.',
   'redirect the advice', 'unsolicited parenting advice', FALSE, TRUE, 370),
  ('tpl_sibling_inheritance', 'Raising a sensitive inheritance topic', 'Family', 'Open a conversation about inheritance or estate planning with a parent or sibling.',
   'I know this isn''t the easiest topic, but I think it''d help all of us to talk through the plan for [topic] sooner rather than later, while we can do it calmly.',
   'open a hard topic calmly', 'inheritance conversation', FALSE, TRUE, 380),
  ('tpl_in_law_boundary', 'Setting a boundary with in-laws', 'Family', 'Push back on an in-law''s involvement without a family rift.',
   'We really appreciate how involved you want to be, and we need to make some of these decisions ourselves — we''ll definitely loop you in when it makes sense.',
   'protect autonomy kindly', 'in-law boundary', FALSE, TRUE, 390),
  ('tpl_lending_family_money', 'Declining to lend money to family', 'Money', 'Say no to a family member''s request for money without shame or guilt.',
   'I''ve thought about it, and I''m not in a position to lend that right now. I know that''s not what you wanted to hear, and I still want to help in other ways if I can.',
   'decline without guilt', 'family money request', FALSE, TRUE, 400),
  ('tpl_estranged_reconnect', 'Reaching out after estrangement', 'Family', 'Reopen contact with an estranged family member cautiously.',
   'I''ve been thinking about reaching out for a while. I''m not expecting anything, just wanted to see if you''d be open to talking, even briefly.',
   'reopen contact carefully', 'estrangement reconnection', FALSE, TRUE, 410),
  ('tpl_roommate_moveout', 'Telling a roommate you''re moving out', 'Living together', 'Give a roommate notice you''re moving out without burning the relationship.',
   'I wanted to let you know as early as I could — I''ve decided to move out, planning to be out by [date]. Want to make sure we handle the lease and logistics together.',
   'give clean notice', 'roommate move-out notice', FALSE, TRUE, 420),
  ('tpl_noise_complaint_neighbor', 'Addressing noise with a neighbor', 'Living together', 'Raise a noise issue with a neighbor without starting a feud.',
   'Hi, I don''t think we''ve properly met — I''m in [unit]. I wanted to mention the noise around [time] has been carrying through the walls; would you mind keeping it down after [time]?',
   'resolve without escalation', 'neighbor noise complaint', FALSE, TRUE, 430),
  ('tpl_shared_chores_uneven', 'Rebalancing shared chores', 'Living together', 'Bring up an uneven chore split with a roommate or partner.',
   'Can we talk through the chore split? I feel like I''ve been picking up more of [task] lately, and I''d like to find something that feels fairer to both of us.',
   'rebalance fairly', 'uneven chore split', FALSE, TRUE, 440),
  ('tpl_guest_overstaying', 'Addressing a roommate''s guest overstaying', 'Living together', 'Raise a partner or friend staying over too often without making it personal.',
   'I love that you two are close, and I want to bring up that [name] has been staying over a lot lately — can we figure out a rhythm that works for the household?',
   'set a household norm', 'overstaying guest', FALSE, TRUE, 450),
  ('tpl_security_deposit_dispute', 'Disputing a security deposit deduction', 'Money', 'Push back on unfair deductions from a security deposit.',
   'I received the deposit breakdown and wanted to dispute the charge for [item] — based on the move-in condition report, this predates my tenancy. Could you review and adjust?',
   'recover the deposit', 'security deposit dispute', FALSE, TRUE, 460),
  ('tpl_declining_volunteer_ask', 'Declining a volunteer commitment', 'Social', 'Say no to a volunteer or committee ask without seeming uninvolved.',
   'I really admire what you''re organizing, and I have to pass this time given my current bandwidth — please keep me in mind for future opportunities.',
   'decline gracefully', 'volunteer commitment decline', FALSE, TRUE, 470),
  ('tpl_group_chat_exit', 'Leaving a group chat gracefully', 'Social', 'Exit a group chat without it seeming like a dramatic statement.',
   'Hey all, I''m going to step out of this chat to cut down on notifications — nothing personal, just simplifying things on my end. Feel free to loop me in directly if needed!',
   'exit without drama', 'group chat exit', FALSE, TRUE, 480),
  ('tpl_friend_venting_boundary', 'Setting a boundary on being a vent target', 'Friendship', 'Ask a friend to dial back constant venting without pushing them away.',
   'I care about you and want to support you, and I''m noticing our conversations have been mostly about [topic] lately — can we find some balance, and maybe also think about additional support for this?',
   'set an emotional boundary', 'friend venting boundary', FALSE, TRUE, 490),
  ('tpl_friend_drifting', 'Reaching out to a friend you''ve drifted from', 'Friendship', 'Reconnect with a friend after a long silence without awkwardness.',
   'I know it''s been a while — life got busy on my end, and I''ve been thinking about you. Would love to catch up if you''re up for it, no explanation needed either way.',
   'rekindle without pressure', 'drifted friendship reconnect', FALSE, TRUE, 500),
  ('tpl_friend_boundary_borrowing', 'Setting a boundary on lending items', 'Friendship', 'Say no to lending something (money, car, item) without feeling like a bad friend.',
   'I love you, but I''ve made it a rule not to lend out [item] — it''s not about trust, it''s just something I''ve decided across the board.',
   'hold a personal rule', 'lending boundary', FALSE, TRUE, 510),
  ('tpl_friend_political_disagreement', 'Navigating a political disagreement with a friend', 'Friendship', 'De-escalate a tense political conversation with a friend without cutting them off.',
   'I don''t think we''re going to agree on this one, and I''d rather protect our friendship than keep going in circles — can we agree to set this topic aside?',
   'de-escalate without ending the friendship', 'political disagreement', FALSE, TRUE, 520),
  ('tpl_customer_complaint', 'Filing a formal customer complaint', 'Work', 'Escalate a service complaint clearly and get a resolution.',
   'I''m writing to formally raise an issue with [service/product] — specifically [issue]. I''d like this resolved by [outcome] and would appreciate a response within [timeframe].',
   'get a resolution', 'customer service complaint', FALSE, TRUE, 530),
  ('tpl_refund_request', 'Requesting a refund firmly', 'Money', 'Ask for a refund clearly without being walked back with excuses.',
   'I''d like to request a full refund for [item/service] due to [reason]. Please let me know the process, and I''d appreciate this being handled without further delay.',
   'get the refund', 'refund request', FALSE, TRUE, 540),
  ('tpl_declining_unpaid_work', 'Declining unpaid ''exposure'' work', 'Work', 'Turn down a request to work for free or ''exposure''.',
   'Thanks for thinking of me for this — I only take on paid work at this stage in my career, so I''ll have to pass unless there''s budget available.',
   'decline unpaid work', 'unpaid work request', FALSE, TRUE, 550),
  ('tpl_teacher_parent_concern', 'Raising a concern with a teacher', 'Family', 'Raise a concern about your child with a teacher constructively.',
   'I wanted to flag something I''ve noticed with [child] regarding [issue] — could we find time to talk through what you''re seeing on your end and how we can support together?',
   'collaborate on a concern', 'teacher-parent concern', FALSE, TRUE, 560),
  ('tpl_coparenting_schedule_change', 'Requesting a co-parenting schedule change', 'Family', 'Propose a change to a custody or co-parenting schedule.',
   'I''d like to propose adjusting the schedule for [date/period] due to [reason]. Want to make sure this works for you too — happy to find a way to make up the time.',
   'propose a change collaboratively', 'co-parenting schedule change', FALSE, TRUE, 570),
  ('tpl_health_boundary_family', 'Declining to discuss a personal health matter', 'Family', 'Decline to share health details with a well-meaning but intrusive relative.',
   'I appreciate you asking, and I''m not really up for going into detail about it right now — I''ll let you know if there''s anything I need from you.',
   'protect privacy kindly', 'health privacy boundary', FALSE, TRUE, 580),
  ('tpl_pet_custody_breakup', 'Deciding pet custody after a breakup', 'Dating', 'Propose a fair arrangement for a shared pet after a breakup.',
   'I know this is a hard conversation, but we should figure out what''s best for [pet] going forward. I was thinking [proposal] — open to hearing what you think is fair too.',
   'resolve fairly', 'pet custody after breakup', FALSE, TRUE, 590),
  ('tpl_wedding_planning_disagreement', 'Navigating a wedding planning disagreement', 'Family', 'Push back on family pressure around wedding planning decisions.',
   'We''ve thought a lot about [decision], and we''ve decided to go with [choice]. I know it''s not what you would have picked, and we''d love your support on it.',
   'hold the decision', 'wedding planning disagreement', FALSE, TRUE, 600),
  ('tpl_declining_moving_help', 'Declining to help someone move', 'Friendship', 'Say no to helping a friend move without feeling guilty.',
   'I wish I could help this weekend, but I''m not able to make it — hope the move goes smoothly, and let me know if there''s another way I can help.',
   'decline without guilt', 'moving help decline', FALSE, TRUE, 610),
  ('tpl_social_media_conflict', 'Addressing a public social media dispute privately', 'Social', 'Move a public disagreement into a private, calmer conversation.',
   'I saw your comment and I don''t think this is the right place to hash it out — can we talk about it directly instead? I''d rather understand where you''re coming from.',
   'de-escalate publicly, resolve privately', 'social media conflict', FALSE, TRUE, 620),
  ('tpl_declining_committee_leadership', 'Declining a leadership role you were nominated for', 'Work', 'Turn down being nominated for a leadership or committee role.',
   'I''m honored to be considered, and I don''t think I can take this on right now given [reason] — I''d be glad to support whoever does take it on.',
   'decline the nomination', 'leadership role decline', FALSE, TRUE, 630)
ON CONFLICT (id) DO NOTHING;

COMMIT;
