-- Migration 012: Expand the Scenario Templates Library past 100 total.
--
-- 010 seeded 8 starter templates, 011 added 54 more (62 total). This
-- adds 43 more across additional everyday scenarios not yet
-- covered — landlord/tenant, ex-partner logistics, blended family,
-- household labor splits, freelance scoping, and more — bringing the
-- total to 105. All premium = FALSE / active = TRUE, visible to
-- every account regardless of plan.
--
-- Depends on: 011_expand_templates.sql

BEGIN;

INSERT INTO templates (id, title, category, description, template_text, goal, scenario, premium, active, sort_order) VALUES
  ('tpl_neighbor_boundary_dog', 'Asking a neighbor to manage their dog', 'Living together', 'Raise a barking or unleashed dog issue with a neighbor without starting a feud.',
   'Hi! I don''t think we''ve officially met — I''m next door. I wanted to mention your dog''s been getting loose/barking around [time], would you mind keeping an eye on that?',
   'resolve without escalation', 'neighbor pet issue', FALSE, TRUE, 700),
  ('tpl_landlord_repair_request', 'Requesting a repair from a landlord', 'Money', 'Push a landlord to actually fix something without sounding like a threat.',
   'Hi [landlord], following up on the [issue] I reported on [date] — it''s still unresolved. Could you let me know a timeline for repair? Happy to coordinate access.',
   'get it fixed', 'landlord repair request', FALSE, TRUE, 710),
  ('tpl_declining_loan_cosign', 'Declining to cosign a loan', 'Money', 'Turn down cosigning a loan for a friend or family member without shame.',
   'I''ve thought this over and I''m not in a position to cosign — it''s not about trusting you, it''s a rule I hold for myself on anything with my name and credit attached.',
   'decline without guilt', 'cosign loan decline', FALSE, TRUE, 720),
  ('tpl_price_increase_notice', 'Notifying a client of a price increase', 'Money', 'Tell an existing client your rates are going up.',
   'Wanted to give you advance notice — starting [date], my rate is moving to [amount] to reflect [reason]. Nothing changes about our current work before then.',
   'raise the price without losing the client', 'price increase notice', FALSE, TRUE, 730),
  ('tpl_declining_discount_request', 'Declining a client''s discount request', 'Money', 'Say no to a client asking for a lower rate without damaging the relationship.',
   'I hear you on budget — I''m not able to go lower on this project, but I''m happy to talk about scoping it down to fit if that helps.',
   'hold your rate', 'discount request decline', FALSE, TRUE, 740),
  ('tpl_gym_membership_cancel', 'Cancelling a gym membership in person', 'Money', 'Firmly cancel a membership despite a retention pitch.',
   'I''d like to cancel my membership effective today, please. I appreciate the offers, but I''ve made my decision — can we go ahead and process it?',
   'cancel without being talked out of it', 'gym membership cancellation', FALSE, TRUE, 750),
  ('tpl_declining_babysit', 'Declining a request to babysit', 'Friendship', 'Say no to watching a friend''s kids without feeling like a bad friend.',
   'I can''t take this one on — hope you''re able to find someone, and let me know for next time if I might be free.',
   'decline without guilt', 'babysitting request decline', FALSE, TRUE, 760),
  ('tpl_asking_to_borrow_car', 'Asking to borrow a friend''s car', 'Friendship', 'Ask to borrow something significant without it feeling like an imposition.',
   'Random ask — any chance I could borrow your car on [date] for [reason]? Totally understand if not, just figured I''d ask.',
   'ask without pressure', 'borrowing a car', FALSE, TRUE, 770),
  ('tpl_friend_repeated_lateness', 'Addressing a friend who''s always late', 'Friendship', 'Bring up chronic lateness without a blow-up.',
   'This isn''t a big deal, but I''ve noticed you''re usually running pretty late when we make plans — could we agree on a buffer, or just be upfront if the time won''t work?',
   'address a pattern calmly', 'friend chronic lateness', FALSE, TRUE, 780),
  ('tpl_friend_unequal_effort', 'Addressing unequal effort in a friendship', 'Friendship', 'Raise the feeling that you''re always the one reaching out.',
   'I''ve noticed I''m usually the one initiating plans lately — not trying to keep score, just wanted to check in on where things stand between us.',
   'raise it without accusation', 'unequal friendship effort', FALSE, TRUE, 790),
  ('tpl_declining_group_project_role', 'Declining an assigned role in a group project', 'Work', 'Push back on being assigned more than your share in a group project.',
   'I can take on [smaller scope], but I don''t think I can also cover [the rest] given my other commitments — can we redistribute that piece?',
   'rebalance the workload', 'group project role decline', FALSE, TRUE, 800),
  ('tpl_reporting_coworker_issue', 'Reporting a coworker''s behavior to HR/manager', 'Work', 'Raise a concern about a colleague''s conduct formally and factually.',
   'I want to flag a pattern I''ve observed with [colleague] regarding [behavior] on [dates]. I''d like to understand how this should be handled.',
   'report factually', 'coworker conduct report', FALSE, TRUE, 810),
  ('tpl_declining_last_minute_request', 'Declining a last-minute work request', 'Work', 'Say no to an unreasonable same-day ask.',
   'I want to help, but I can''t turn this around today given [reason]. I could have it by [realistic time] — would that work, or does it need to go to someone else?',
   'decline the timeline, not the task', 'last-minute work request', FALSE, TRUE, 820),
  ('tpl_asking_for_written_confirmation', 'Asking for something in writing', 'Work', 'Politely insist a verbal agreement be put in writing.',
   'Just to make sure we''re aligned, could you send that over in writing/email? Just want to make sure we''re both working from the same understanding.',
   'get it documented', 'request written confirmation', FALSE, TRUE, 830),
  ('tpl_declining_scope_change_deadline', 'Pushing back on a compressed deadline', 'Work', 'Push back on a shortened deadline without seeming uncooperative.',
   'Hitting [new date] isn''t realistic without cutting [specific things] — I can either deliver a reduced version by then, or the full version by [realistic date]. Which do you prefer?',
   'negotiate the tradeoff', 'deadline pushback', FALSE, TRUE, 840),
  ('tpl_asking_manager_for_feedback', 'Asking your manager for honest feedback', 'Work', 'Proactively request candid feedback instead of waiting for a review cycle.',
   'Do you have 15 minutes sometime this week? I''d like honest feedback on how I''m doing — specifically what''s working and what I should be doing differently.',
   'get real feedback', 'request manager feedback', FALSE, TRUE, 850),
  ('tpl_declining_friend_business_pitch', 'Declining a friend''s business pitch or MLM', 'Money', 'Say no to investing in or joining a friend''s business venture.',
   'I''ve thought about it, and this isn''t something I want to get into financially. I still want to support you as a friend, just not in this way.',
   'decline the pitch, keep the friendship', 'business pitch decline', FALSE, TRUE, 860),
  ('tpl_splitting_inheritance_items', 'Discussing splitting sentimental items with siblings', 'Family', 'Navigate dividing sentimental belongings after a parent''s passing or downsizing.',
   'I know this is hard for all of us. Can we sit down and go through [items] together so everyone gets a say, rather than deciding separately?',
   'navigate fairly and gently', 'dividing sentimental items', FALSE, TRUE, 870),
  ('tpl_asking_parents_for_space', 'Asking parents for more independence', 'Family', 'Ask parents to back off on a specific area of your life.',
   'I know you''re coming from a place of care, and I need to handle [area] on my own for a while — I''ll ask if I need help.',
   'assert independence kindly', 'asking for independence', FALSE, TRUE, 880),
  ('tpl_addressing_parent_favoritism', 'Raising a feeling of parental favoritism', 'Family', 'Bring up a perception of favoritism between siblings to a parent.',
   'I want to bring something up that''s been sitting with me — I''ve felt like [sibling] gets treated differently in [way], and I wanted to talk about it rather than let it build.',
   'raise it honestly', 'perceived favoritism', FALSE, TRUE, 890),
  ('tpl_step_family_boundary', 'Setting a boundary with a step-parent/step-child', 'Family', 'Navigate a boundary in a blended family relationship.',
   'I want us to have a good relationship, and I need you to let me handle [specific decision] on my own — I hope you can understand that.',
   'set a boundary in a blended family', 'step-family boundary', FALSE, TRUE, 900),
  ('tpl_asking_ex_for_belongings', 'Asking an ex to return your belongings', 'Dating', 'Request the return of personal items after a breakup, keeping it businesslike.',
   'Hey — when you get a chance, could you drop off [items] or let me know a time I can grab them? Trying to get this wrapped up.',
   'handle logistics cleanly', 'retrieving belongings from ex', FALSE, TRUE, 910),
  ('tpl_declining_reconciliation', 'Declining to get back together with an ex', 'Dating', 'Turn down a request to reconcile clearly and finally.',
   'I''ve thought about this seriously, and I don''t think getting back together is right for me. I wanted to give you a real answer instead of leaving it open.',
   'decline clearly and finally', 'declining reconciliation', FALSE, TRUE, 920),
  ('tpl_bringing_up_exclusivity', 'Bringing up exclusivity while dating', 'Dating', 'Ask to become exclusive without pressuring an immediate answer.',
   'I''ve really enjoyed getting to know you, and I''d like to be exclusive if you''re feeling the same way — no pressure if you need to think about it.',
   'propose exclusivity', 'dating exclusivity', FALSE, TRUE, 930),
  ('tpl_addressing_partner_spending', 'Raising a concern about a partner''s spending', 'Dating', 'Bring up financial habits with a partner without it becoming a fight.',
   'Can we talk about money stuff sometime this week? I''ve been noticing some patterns in our spending and want to figure out a plan together, not point fingers.',
   'open a money conversation', 'partner spending concern', FALSE, TRUE, 940),
  ('tpl_long_distance_checkin', 'Proposing a check-in about a long-distance relationship', 'Dating', 'Raise doubts or logistics questions about a long-distance relationship.',
   'I''ve been thinking about us and the distance, and I want to talk honestly about how we''re both feeling about it and what the plan looks like.',
   'open an honest check-in', 'long-distance relationship check-in', FALSE, TRUE, 950),
  ('tpl_declining_social_media_add', 'Declining to add a coworker on personal social media', 'Work', 'Turn down a friend/follow request from a colleague you''d rather keep separate.',
   'I try to keep my personal social media pretty separate from work — nothing personal, it''s just a boundary I keep across the board!',
   'decline the boundary crossing', 'social media request decline', FALSE, TRUE, 960),
  ('tpl_asking_for_pay_transparency', 'Asking a colleague about pay transparency', 'Work', 'Ask a peer about compensation to check for pay equity.',
   'This might be an odd ask, but would you be open to sharing roughly what band you''re in? Trying to get a read on whether my comp is fair.',
   'get information carefully', 'pay transparency ask', FALSE, TRUE, 970),
  ('tpl_declining_unpaid_overtime', 'Declining to work unpaid overtime', 'Work', 'Push back on being expected to work off the clock.',
   'I''m not able to take this on outside of my hours without it being compensated — happy to prioritize it first thing tomorrow instead.',
   'protect your time', 'unpaid overtime decline', FALSE, TRUE, 980),
  ('tpl_addressing_micromanagement', 'Addressing a manager''s micromanagement', 'Work', 'Raise feeling micromanaged with your manager constructively.',
   'I wanted to check in on how we''re working together — I think I''d be more effective with a bit more autonomy on [area]. Can we talk about what that could look like?',
   'raise it constructively', 'micromanagement concern', FALSE, TRUE, 990),
  ('tpl_declining_friend_request_money_again', 'Declining a repeat request to borrow money', 'Friendship', 'Say no to lending money again to someone who hasn''t repaid before.',
   'I''m not able to lend again this time — the last loan is still outstanding, and I need to hold that line for myself.',
   'hold a firm boundary', 'repeat money request decline', FALSE, TRUE, 1000),
  ('tpl_asking_roommate_for_rent', 'Asking a roommate for their share of rent', 'Living together', 'Ask a roommate for overdue rent without a blow-up.',
   'Hey, just checking in — rent was due on [date] and I haven''t gotten your share yet. Can you send it over or let me know what''s going on?',
   'get paid on time', 'roommate rent request', FALSE, TRUE, 1010),
  ('tpl_declining_houseguest', 'Declining to host a long-term houseguest', 'Living together', 'Say no to someone wanting to stay with you for an extended period.',
   'I''ve thought about it, and I don''t think I can host for that long right now — I hope you''re able to find something that works.',
   'decline hosting', 'long-term houseguest decline', FALSE, TRUE, 1020),
  ('tpl_addressing_shared_car_use', 'Addressing uneven use of a shared car', 'Living together', 'Raise an issue about how a shared vehicle is being used or maintained.',
   'Can we set some ground rules for the car? I''ve noticed [issue] and want to figure out something fair for both of us going forward.',
   'set shared rules', 'shared car use', FALSE, TRUE, 1030),
  ('tpl_declining_charity_ask', 'Declining a request to donate', 'Social', 'Say no to a fundraising or donation ask without guilt.',
   'I''m not able to contribute to this one, but I appreciate you thinking of me — wishing you luck with the campaign.',
   'decline a donation ask', 'charity donation decline', FALSE, TRUE, 1040),
  ('tpl_addressing_group_chat_conflict', 'De-escalating a group chat argument', 'Social', 'Calm down an escalating argument happening in a group chat.',
   'I think this is getting heated — can we table this here and anyone who wants to keep talking about it can do so 1:1?',
   'de-escalate a group conflict', 'group chat argument', FALSE, TRUE, 1050),
  ('tpl_declining_uninvited_advice', 'Declining unsolicited advice from a friend', 'Friendship', 'Push back gently on a friend who keeps giving advice you didn''t ask for.',
   'I appreciate you caring, and honestly right now I just need to vent, not get advice — is that okay?',
   'redirect unsolicited advice', 'unsolicited advice pushback', FALSE, TRUE, 1060),
  ('tpl_asking_friend_to_repay_favor', 'Asking a friend to return a favor', 'Friendship', 'Ask someone to follow through on something they offered to do for you.',
   'Hey, you''d mentioned helping with [thing] a while back — any chance you''re still up for it? No worries if timing''s changed.',
   'collect on an offer', 'asking friend for favor', FALSE, TRUE, 1070),
  ('tpl_declining_third_wheel_invite', 'Declining an invite where you''d be a third wheel', 'Social', 'Turn down hanging out with a couple without it being awkward.',
   'Thanks for the invite, but I think I''ll sit this one out — you two enjoy! Let''s find a time for just us soon.',
   'decline gracefully', 'third wheel invite decline', FALSE, TRUE, 1080),
  ('tpl_negotiating_freelance_scope', 'Pushing back on unclear freelance scope', 'Work', 'Get scope clarified before starting freelance work.',
   'Before I start, I want to make sure scope is clear — can we nail down exactly what''s included so we''re both aligned on expectations?',
   'clarify scope upfront', 'freelance scope clarification', FALSE, TRUE, 1090),
  ('tpl_declining_photo_post', 'Asking someone to take down a photo of you', 'Social', 'Ask a friend to remove or not post a photo of you.',
   'Hey, would you mind taking that photo down? I''m just not comfortable with it being up — appreciate you understanding.',
   'request photo removal', 'photo takedown request', FALSE, TRUE, 1100),
  ('tpl_addressing_partner_household_split', 'Raising an uneven household labor split with a partner', 'Dating', 'Bring up an unfair division of household responsibilities with a partner.',
   'Can we talk about how we''re splitting things at home? I''ve been feeling like it''s uneven lately and want to figure out something that works for both of us.',
   'rebalance household labor', 'household labor split', FALSE, TRUE, 1110),
  ('tpl_declining_wedding_party_role', 'Declining to be in someone''s wedding party', 'Social', 'Turn down being a bridesmaid/groomsman without damaging the friendship.',
   'I''m so honored you''d ask, and I have to say no given [reason] — I still want to be there celebrating you on the day.',
   'decline an honor gracefully', 'wedding party decline', FALSE, TRUE, 1120)
ON CONFLICT (id) DO NOTHING;

COMMIT;
